// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/config_service.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_proto_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_proto_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

var File_proto_config_service_proto protoreflect.FileDescriptor

const file_proto_config_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/config_service.proto\x12\x06config\"5\n" +
	"\x10GetConfigRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"4\n" +
	"\x11GetConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson2Q\n" +
	"\rConfigService\x12@\n" +
	"\tGetConfig\x12\x18.config.GetConfigRequest\x1a\x19.config.GetConfigResponseB4Z2github.com/SavanRajyaguru/ecommerce-go-config-service/protob\x06proto3"

var (
	file_proto_config_service_proto_rawDescOnce sync.Once
	file_proto_config_service_proto_rawDescData []byte
)

func file_proto_config_service_proto_rawDescGZIP() []byte {
	file_proto_config_service_proto_rawDescOnce.Do(func() {
		file_proto_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_service_proto_rawDesc), len(file_proto_config_service_proto_rawDesc)))
	})
	return file_proto_config_service_proto_rawDescData
}

var file_proto_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_config_service_proto_goTypes = []any{
	(*GetConfigRequest)(nil),  // 0: config.GetConfigRequest
	(*GetConfigResponse)(nil), // 1: config.GetConfigResponse
}
var file_proto_config_service_proto_depIdxs = []int32{
	0, // 0: config.ConfigService.GetConfig:input_type -> config.GetConfigRequest
	1, // 1: config.ConfigService.GetConfig:output_type -> config.GetConfigResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_config_service_proto_init() }
func file_proto_config_service_proto_init() {
	if File_proto_config_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_service_proto_rawDesc), len(file_proto_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_service_proto_goTypes,
		DependencyIndexes: file_proto_config_service_proto_depIdxs,
		MessageInfos:      file_proto_config_service_proto_msgTypes,
	}.Build()
	File_proto_config_service_proto = out.File
	file_proto_config_service_proto_goTypes = nil
	file_proto_config_service_proto_depIdxs = nil
}
